tool: cmake
msvs: 2017
arch: x86_64

steps:
  - configure
  - cpplint
  - make
  - install
  - test
cpplint:
  - .option:
     filter:
       - -whitespace/tab
       - -build/header_guard
       - -whitespace/braces
       - -readability/casting
       - -build/include_order
       - -build/include
     linelength: 120
     sources:
       - lib/*/*.h
       - lib/*/*.cc

project:
  - libwebstreamer:
      location: '${__directory__}'